/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.practica.banca_1.interfaces;

import ec.edu.espe.practica.banca_1.clases.Clientes;
import ec.edu.espe.practica.banca_1.clases.Movimientos;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author jeffe
 */
public class JDMovimientos extends javax.swing.JDialog {
   Date now = new Date(System.currentTimeMillis());
    SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
    String fecha = String.valueOf(date);
    Movimientos obj;
    Clientes cli;
    java.util.Date dt = new java.util.Date();
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    String currentTime = sdf.format(dt);
    /**
     * Creates new form JDMovimientos1
     */
    public JDMovimientos(java.awt.Frame parent, boolean modal) {
         super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        obj = new Movimientos();
        obj.generarCodigo(txtCodigo);
        txtFecha.setText(currentTime);
        cli = new Clientes();
        jcmbTipo.enable(false);
        txtMonto.enable(false);
    }
     public void Limpiar(){        
        txtCodigo.setText("");
        txtFecha.setText("");
        txtMonto.setText("");
        txtSaldo.setText("");
        jcmbCuenta.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMantenimientoTitulo = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblIngresarID = new javax.swing.JLabel();
        txtBuscarCI = new javax.swing.JTextField();
        btnClienteBuscarCI = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        btnMovEliminar = new javax.swing.JButton();
        btnMovGuardar = new javax.swing.JButton();
        btnMovNuevo = new javax.swing.JButton();
        btnMovSalir = new javax.swing.JButton();
        jcmbCuenta = new javax.swing.JComboBox<>();
        pnlDatosMov = new javax.swing.JPanel();
        jcmbTipo = new javax.swing.JComboBox<>();
        txtCodigoCuenta = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        lblMantenimientoTipo = new javax.swing.JLabel();
        lblMantenimientoStock = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        lblMantenimientoNombre = new javax.swing.JLabel();
        lblMantenimientoCodigo = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        lblMantenimientoCodigo2 = new javax.swing.JLabel();
        lblMantenimientoTipo1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMantenimientoTitulo.setBackground(new java.awt.Color(204, 204, 204));
        pnlMantenimientoTitulo.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 35)); // NOI18N
        jLabel1.setText("MOVIMIENTOS");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\DiegoYandun\\Documents\\NetBeansProjects\\Cooperativa02_Grupo05\\src\\main\\java\\ec\\edu\\espe\\practica\\banca_1\\imagenes\\prestamos2.png")); // NOI18N

        javax.swing.GroupLayout pnlMantenimientoTituloLayout = new javax.swing.GroupLayout(pnlMantenimientoTitulo);
        pnlMantenimientoTitulo.setLayout(pnlMantenimientoTituloLayout);
        pnlMantenimientoTituloLayout.setHorizontalGroup(
            pnlMantenimientoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMantenimientoTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(pnlMantenimientoTituloLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(19, 19, 19))
        );
        pnlMantenimientoTituloLayout.setVerticalGroup(
            pnlMantenimientoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMantenimientoTituloLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(pnlMantenimientoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblIngresarID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIngresarID.setText("Ingresar CI:");

        txtBuscarCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarCIActionPerformed(evt);
            }
        });
        txtBuscarCI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarCIKeyTyped(evt);
            }
        });

        btnClienteBuscarCI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClienteBuscarCI.setIcon(new javax.swing.ImageIcon("C:\\Users\\DiegoYandun\\Documents\\NetBeansProjects\\Cooperativa02_Grupo05\\src\\main\\java\\ec\\edu\\espe\\practica\\banca_1\\imagenes\\Search.png")); // NOI18N
        btnClienteBuscarCI.setText("Buscar");
        btnClienteBuscarCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteBuscarCIActionPerformed(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(255, 255, 255));

        btnMovEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMovEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\DiegoYandun\\Documents\\NetBeansProjects\\Cooperativa02_Grupo05\\src\\main\\java\\ec\\edu\\espe\\practica\\banca_1\\imagenes\\eliminar.png")); // NOI18N
        btnMovEliminar.setText("Eliminar");
        btnMovEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovEliminarActionPerformed(evt);
            }
        });

        btnMovGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMovGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\DiegoYandun\\Documents\\NetBeansProjects\\Cooperativa02_Grupo05\\src\\main\\java\\ec\\edu\\espe\\practica\\banca_1\\imagenes\\guardarCliente.png")); // NOI18N
        btnMovGuardar.setText("Guardar");
        btnMovGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovGuardarActionPerformed(evt);
            }
        });

        btnMovNuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMovNuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\DiegoYandun\\Documents\\NetBeansProjects\\Cooperativa02_Grupo05\\src\\main\\java\\ec\\edu\\espe\\practica\\banca_1\\imagenes\\escoba.png")); // NOI18N
        btnMovNuevo.setText("Limpiar");
        btnMovNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovNuevoActionPerformed(evt);
            }
        });

        btnMovSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMovSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\DiegoYandun\\Documents\\NetBeansProjects\\Cooperativa02_Grupo05\\src\\main\\java\\ec\\edu\\espe\\practica\\banca_1\\imagenes\\salirCoche.png")); // NOI18N
        btnMovSalir.setText("Salir");
        btnMovSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMovGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMovEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMovNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(btnMovSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMovGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMovNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMovSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMovEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(152, 152, 152))
        );

        jcmbCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbCuentaActionPerformed(evt);
            }
        });

        pnlDatosMov.setBackground(new java.awt.Color(149, 149, 149));

        jcmbTipo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jcmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retiro", "Depósito" }));

        txtCodigoCuenta.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtCodigoCuenta.setEnabled(false);

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtCodigo.setEnabled(false);

        lblMantenimientoTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMantenimientoTipo.setText("Tipo:");

        lblMantenimientoStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMantenimientoStock.setText("Saldo:");

        txtSaldo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtSaldo.setEnabled(false);

        lblMantenimientoNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMantenimientoNombre.setText("Monto:");

        lblMantenimientoCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMantenimientoCodigo.setText("Codigo:");

        txtMonto.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });

        lblMantenimientoCodigo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMantenimientoCodigo2.setText("Codigo Cuenta:");

        lblMantenimientoTipo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMantenimientoTipo1.setText("Fecha:");

        txtFecha.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtFecha.setEnabled(false);

        javax.swing.GroupLayout pnlDatosMovLayout = new javax.swing.GroupLayout(pnlDatosMov);
        pnlDatosMov.setLayout(pnlDatosMovLayout);
        pnlDatosMovLayout.setHorizontalGroup(
            pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosMovLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosMovLayout.createSequentialGroup()
                        .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMantenimientoNombre)
                            .addComponent(lblMantenimientoTipo1)
                            .addComponent(lblMantenimientoTipo)
                            .addComponent(lblMantenimientoStock, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(68, 68, 68)
                        .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMonto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcmbTipo, 0, 125, Short.MAX_VALUE)
                            .addComponent(txtSaldo)))
                    .addGroup(pnlDatosMovLayout.createSequentialGroup()
                        .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMantenimientoCodigo2)
                            .addComponent(lblMantenimientoCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txtCodigo))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pnlDatosMovLayout.setVerticalGroup(
            pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosMovLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMantenimientoCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMantenimientoCodigo2)
                    .addComponent(txtCodigoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosMovLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblMantenimientoTipo))
                    .addGroup(pnlDatosMovLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jcmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMantenimientoTipo1)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMantenimientoNombre)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMantenimientoStock))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMantenimientoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDatosMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIngresarID, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcmbCuenta, 0, 152, Short.MAX_VALUE)
                            .addComponent(txtBuscarCI))
                        .addGap(18, 18, 18)
                        .addComponent(btnClienteBuscarCI, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMantenimientoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscarCI, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIngresarID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcmbCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnClienteBuscarCI)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatosMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarCIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCIKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'||c>'9'){
            evt.consume();
        }else{
            if(txtBuscarCI.getText().length() > 13){
                evt.consume();
                JOptionPane.showMessageDialog(null, "Dato ingresado incorrecto");
            }
        }
    }//GEN-LAST:event_txtBuscarCIKeyTyped

    private void btnClienteBuscarCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteBuscarCIActionPerformed
        try{
            if(txtBuscarCI.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Debe ingresar el número de cédula.");
            }else{
                if(cli.validarCedula(txtBuscarCI.getText()) == true){
                    obj.buscarCuenta(jcmbCuenta,txtBuscarCI.getText());
                    txtBuscarCI.setText("");
                    jcmbTipo.enable(true);
                    txtMonto.enable(true);
                }else{
                    txtBuscarCI.setText("");
                }
            }
        }catch (Exception ex){

        }
    }//GEN-LAST:event_btnClienteBuscarCIActionPerformed

    private void btnMovEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMovEliminarActionPerformed

    private void btnMovGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovGuardarActionPerformed
        String tipo = jcmbTipo.getSelectedItem().toString().substring(0,3).toUpperCase();
        float monto = Float.parseFloat(txtMonto.getText());
        txtSaldo.setText("0.00");
        Movimientos obj = new Movimientos(txtCodigoCuenta.getText(),tipo,monto,Float.parseFloat(txtSaldo.getText()));
        obj.registrarMov(txtSaldo,txtCodigo.getText());
    }//GEN-LAST:event_btnMovGuardarActionPerformed

    private void btnMovNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovNuevoActionPerformed
        Limpiar();
        btnMovGuardar.setEnabled(true);
    }//GEN-LAST:event_btnMovNuevoActionPerformed

    private void btnMovSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnMovSalirActionPerformed

    private void jcmbCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbCuentaActionPerformed
        txtCodigoCuenta.setText(jcmbCuenta.getSelectedItem().toString());
    }//GEN-LAST:event_jcmbCuentaActionPerformed

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'&&evt.getKeyChar()!='-'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&& txtMonto.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_txtMontoKeyTyped

    private void txtBuscarCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDMovimientos dialog = new JDMovimientos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteBuscarCI;
    private javax.swing.JButton btnMovEliminar;
    private javax.swing.JButton btnMovGuardar;
    private javax.swing.JButton btnMovNuevo;
    private javax.swing.JButton btnMovSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jcmbCuenta;
    private javax.swing.JComboBox<String> jcmbTipo;
    private javax.swing.JLabel lblIngresarID;
    private javax.swing.JLabel lblMantenimientoCodigo;
    private javax.swing.JLabel lblMantenimientoCodigo2;
    private javax.swing.JLabel lblMantenimientoNombre;
    private javax.swing.JLabel lblMantenimientoStock;
    private javax.swing.JLabel lblMantenimientoTipo;
    private javax.swing.JLabel lblMantenimientoTipo1;
    private java.awt.Panel panel1;
    private javax.swing.JPanel pnlDatosMov;
    private java.awt.Panel pnlMantenimientoTitulo;
    private javax.swing.JTextField txtBuscarCI;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoCuenta;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
